version: "3.8"

services:
  payload:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - pnpm_store:/home/node/.pnpm-store
    working_dir: /home/node/app
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: payload_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongodb_data:/data/db
    logging:
      driver: none

volumes:
  mongodb_data:
  node_modules:
  pnpm_store:
