version: "3.8"

services:
  payload:
    build:
      context: .
      target: runtime
    container_name: payload_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - pnpm_store:/home/node/.pnpm-store
      - node_modules:/home/node/app/node_modules
      - ./public/media:/home/node/app/public/media # persistent uploads

    # 👇 Add this block:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payload.rule=Host(`r048wo004kgsgk4404k8gc80.91.99.170.52.sslip.io`)"
      - "traefik.http.routers.payload.entrypoints=web"
      - "traefik.http.services.payload.loadbalancer.server.port=3000"
      # Route /media through the same service
      - "traefik.http.routers.payload-media.rule=Host(`r048wo004kgsgk4404k8gc80.91.99.170.52.sslip.io`) && PathPrefix(`/media`)"
      - "traefik.http.routers.payload-media.entrypoints=web"
      - "traefik.http.routers.payload-media.service=payload"

  mongo:
    image: mongo:latest
    container_name: payload_mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    command:
      - --storageEngine=wiredTiger
    logging:
      driver: none

volumes:
  mongodb_data:
  pnpm_store:
  node_modules:
