version: "3.8"

services:
  payload:
    build:
      context: .
      target: runtime
    container_name: payload_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./public/media:/home/node/app/public/media # persistent uploads

volumes:
  # Only needed if you want to persist media uploads outside the container
